apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-ceph-operator-config
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  CSI_PLUGIN_TOLERATIONS: |
    - key: node.ocs.openshift.io/storage
      operator: Equal
      value: "true"
      effect: NoSchedule
    - key: node-role.kubernetes.io/infra
      operator: Exists
      effect: NoSchedule